services:
  app:
    build: .
    image: leminhthe04/game-server:latest
    ports:
      - "8080:8080" # Spring HTTP server
      - "8386:8386" # WebSocket server
    depends_on:
      mongo:
        condition: service_healthy   # <--- Đợi Mongo healthy mới chạy
      redis:
        condition: service_started
    environment:
      - TZ=Asia/Ho_Chi_Minh
    env_file:        # 
      - .env         # Báo cho Docker biết hãy nạp các biến từ file .env vào container
    volumes:
      - ./logs:/app/logs

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:                     # <--- Thêm bộ kiểm tra sức khỏe
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      

  redis:
    image: redis:7
    ports:
      - "6379:6379"


volumes:
  mongo_data: