services:
  app:
    build: .
    image: leminhthe04/game-server:latest
    ports:
      - "8080:8080" # Spring HTTP server
      - "8386:8386" # WebSocket server
    depends_on:
      - mongo
      - redis
    env_file:        # 
      - .env         # Báo cho Docker biết hãy nạp các biến từ file .env vào container

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      

  redis:
    image: redis:7
    ports:
      - "6379:6379"


volumes:
  mongo_data: